### ISSUE TITLE
error: Error: Unable to resolve module ./auth0-configuration from auth0-react-native-sample/00-Login-Hooks/app/App.js: 

### ISSUE THREAD

**Issue by hiftikha** [auth0-samples/auth0-react-native-sample#111]
I am getting the following error when trying to spin up the Android up while the metro bundler server is running 

`None of these files exist:
  * app/auth0-configuration(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * app/auth0-configuration/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  10 | import {Alert, Button, StyleSheet, Text, View} from 'react-native';
  11 | import {useAuth0, Auth0Provider} from 'react-native-auth0';
> 12 | import config from './auth0-configuration';
     |                     ^
  13 |
`

**Comment by poovamraj** [comment]
@hiftikha You have to check out this step - https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login-Hooks#2-configure-auth0. Looks like you haven't removed `.example` from `app/auth0-configuration.js.example`
