### ISSUE TITLE
docs are outdated 

### ISSUE THREAD

**Issue by ah0y** [auth0-samples/auth0-react-native-sample#114]
After the change introduced [here](https://github.com/auth0-samples/auth0-react-native-sample/pull/113) the docs were never updated to indicate that a scheme is now required:

https://github.com/auth0-samples/auth0-react-native-sample/blob/3120576430bbe81e4906f1a2ada5cc06bf24120c/00-Login-Expo/README.md?plain=1#L55-L56

**Comment by poovamraj** [comment]
Hi @ah0y 👋 Thanks for raising this. I have fixed this issue in the PR above. Really great callout. Will close this issue now. Feel free to add more suggestions to the PR!
