### ISSUE TITLE
Expo Router 2 example

### ISSUE THREAD

**Issue by ogmzh** [auth0-samples/auth0-react-native-sample#131]
### Checklist

- [X] I have looked into the Readme ([Base](https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login#readme)/[Hooks](https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login-Hooks#readme)/[Expo](https://github.com/auth0-samples/auth0-react-native-sample/tree/master/00-Login-Expo#readme)) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0-samples/auth0-react-native-sample/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I'm having issues grasping how the callback routing works with Auth0 and the new expo file based router (expo router 2) which is now stable and merged to expo. 

### Describe the ideal solution

Would love a working example of integrating new 3.0 auth0 with expo router 2.

**Comment by poovamraj** [comment]
Hi @ogmzh there shouldn't be much change in how Auth0 is integrated depending on the router. Are you facing any issues and can you explain it in more detail here?

**Comment by ogmzh** [comment]
@poovamraj the API and the router mounting protected routes has changed a bit so that's mostly what I struggled with, but it's all good now :)
