### ISSUE TITLE
No instructions to execute the sample

### ISSUE THREAD

**Issue by rafanog** [auth0-samples/auth0-react-native-sample#19]
The README.md file included within the sample while downloaded doesn't include any instructions nor prerequisites to execute it

**Comment by cocojoe** [comment]
It links to the Login Quickstart which should always be the source of truth, I don't see the need to duplicate it and then maintain two copies.

https://github.com/auth0-samples/auth0-react-native-sample/blob/master/00-Login/README.md#auth0-react-native-samples---login
