### ISSUE TITLE
Figuring out the ".. address is invalid" error.

### ISSUE THREAD

**Issue by wadewegner** [auth0-samples/auth0-react-native-sample#21]
I get the error "Safari cannot open the page because the address is invalid." when attempting to use your library, after successfully logging in:

![image](https://user-images.githubusercontent.com/746259/44681018-2f91d180-a9f4-11e8-92b0-c4a11b5e6f8c.png)

Any pointers on how to resolve?

**Comment by wadewegner** [comment]
It was a mistake on my part. Closing.

**Comment by jbuck94** [comment]
@wadewegner what was the mistake you made? I am seeing the same issue
