### ISSUE TITLE
Auth0 React Native Not Compatible with Current Expo CLI

### ISSUE THREAD

**Issue by jt-singularity** [auth0-samples/auth0-react-native-sample#30]
I had an issue setting up auth0-react-native login with a react native project started using Expo. Because the current Expo CLI uses react native 0.59 you cannot use pod install to link dependencies. I created this issue in the auth0 community forum and suggested this be integrated into the docs of this project:

https://community.auth0.com/t/react-native-quick-start-not-working/34039

I was asked to also post the issue here.

Thanks!

**Comment by GuyAvraham** [comment]
https://github.com/expo/auth0-example
But you will have to upgrade to expo36 using the upgrade guide on expo-docs

**Comment by Widcket** [comment]
Thanks @GuyAvraham!

**Comment by GuyAvraham** [comment]
https://github.com/GuyAvraham/expo-auth0-example-2020
This is an updated version...
@Widcket

**Comment by Widcket** [comment]
The expo exanmple has moved: https://github.com/expo/examples/tree/master/with-auth0
