### ISSUE TITLE
Missing support for android TV app using react native

### ISSUE THREAD

**Issue by techseria** [auth0-samples/auth0-react-native-sample#35]
I am working on android TV app using react native. I have integrated the Auth0 in this app using `react-native-auth0` as mentioned in the documentation of Auth0. I have two issues here.
1. After configuring the dashboard and the app as per documentation I am getting the error. it says "access_denied: unable to access client_id from undefined".
2. In this sample you have used web based authentication which I think will not be supported on the TV.

can you look in this and guide me please?

**Comment by lbalmaceda** [comment]
@techseria device flows are not yet supported by this SDK. But if you're feeling adventurous, here's some guidance on how it should be performed https://auth0.com/docs/flows/concepts/device-auth
