### ISSUE TITLE
access_denied: Unauthorized

### ISSUE THREAD

**Issue by deep24kumar24** [auth0-samples/auth0-react-native-sample#41]
I have followed the tutorial given here: https://auth0.com/docs/quickstart/native/react-native

Created a sample app, 
After click on button browser opens up with AUTH0, login and signup page of my app,
but after login or signup, I am getting `access_denied: Unauthorized` on console.

This is the code snippet that is on button click, 
` auth0
                  .webAuth
                  .authorize({scope: 'openid profile email'})
                  .then(credentials =>
                    // Successfully authenticated
                    console.log("Logged In")
                  )
                  .catch(error => console.log("Error -",error))
              }
`
It falls in catch.
![image](https://user-images.githubusercontent.com/23245824/93095614-5372ef00-f671-11ea-93bf-d16fd323fd66.png)

**Comment by shawndoyle** [comment]
+1 Having the same issue

**Comment by tlow92** [comment]
Have to set application type to native in auth0 application configuration.
