### ISSUE TITLE
The provided scheme is not valid. A scheme should not include special characters such as ":" or "/".' was thrown

### ISSUE THREAD

**Issue by heyms** [auth0-samples/auth0-react-native-sample#45]
After putting these value in info.plist I'm getting issue in iOS but in case of Android It's working fine.

The provided scheme is not valid. A scheme should not include special characters such as ":" or "/".' was thrown while invoking showUrl on target A0Auth0 with params.

<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleTypeRole</key>
        <string>None</string>
        <key>CFBundleURLName</key>
        <string>auth0</string>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
        </array>
    </dict>
</array>

 "react": "17.0.2",
 "react-native": "0.64.0",

![Simulator Screen Shot - iPhone 12 - 2021-04-15 at 13 11 35](https://user-images.githubusercontent.com/9988256/114854021-02db9400-9e02-11eb-89ab-2194f5d39a80.png)

**Comment by Widcket** [comment]
Hi @heyms, thanks for raising this. Which version of Xcode are you using?

**Comment by heyms** [comment]
Version 12.5 beta 3 (12E5244e)

**Comment by Widcket** [comment]
We need to update the React Native SDK to support Xcode 12.5, I expect to put up a PR soon.

**Comment by relm923** [comment]
This appears to be happening consistently on iOS 14.5 now

**Comment by idrisssakhi** [comment]
Hello, i have the same issue here; running in ios 14.5. any workarround

**Comment by heyms** [comment]
Please check for 14.4 version

**Comment by relm923** [comment]
The error does not occur on 14.4

**Comment by heyms** [comment]
Great !

**Comment by Widcket** [comment]
The PR with the fix for the SDK is up: https://github.com/auth0/react-native-auth0/pull/369.
After that is merged and released, we'll need to update this sample.

**Comment by fzaffarana** [comment]
I have the same problem using version `1.6.0` (react-native-auth0). 

My problem is that I can't update it because the project is using version `0.59.9` of rn. (version `1.6.0` is a fixed version for `v0.59.9` of rn based on the documentation)

is there any fix for this version?
