### ISSUE TITLE
Fatal error during runtime when launching app

### ISSUE THREAD

**Issue by mikearias3** [auth0-samples/auth0-react-native-sample#5]
**Environment Information**
Browser: Google Chrome v58 for Mac
Samples: https://github.com/auth0-samples/auth0-ios-objc-sample
Xcode: 8.3.2
React-Native: 2.0.1

**Description**
After building the app, the screen immediately turns red and a fatal error shows up.

**Screenshot**
<img width="945" alt="screen shot 2017-08-09 at 11 13 02 pm" src="https://user-images.githubusercontent.com/5594487/29153035-080c9488-7d59-11e7-841c-92e198762dfe.png">

**Comment by cocojoe** [comment]
Check out the latest sample and check you've set it up correctly looking at the QS https://auth0.com/docs/quickstart/native/react-native

Report if you still have issues, thx.
