### ISSUE TITLE
Facing issues with `Sign in With Apple` 

### ISSUE THREAD

**Issue by aakanshu** [auth0-samples/auth0-react-native-sample#57]
Hi There,

I want to implement Sign in with Apple, similar to Sign in with Google. I've setup the connection and linked it to my app in Auth0 portal.
In code when I'm passing connection as `apple`  it is throwing error, error message:

> [server_error: Object argument required.] 

Here is my method which I'm calling on clicking the `Sign In with Apple` Button

>
     auth0.webAuth
      .authorize({
        audience: config.API_BASE_URL,
        connection:'apple',
        scope: 'openid profile email offline_access',
      })
      .then(async credentials => {
        console.log("Success");
      })
      .catch(error => {
         console.log(error);
       });

**Comment by poovamraj** [comment]
Hi @aakanshu, Have you tried the solution mentioned in this [post](https://community.auth0.com/t/native-ios-xamarin-sign-in-with-apple-issue-server-error/65128/3)

**Comment by aakanshu** [comment]
Hi @poovamraj ,
I've went through the above post. In my case I'm using the default developer credentials provided by auth0, my idea was to use dev (default) credentials so that I can quickly test it and in prod do the setup.

**Comment by poovamraj** [comment]
Oh okay. Under Authentication > Social > apple you should be able to find a button called Try Connection. Can you verify whether it is working there properly?

Also can you let us know whether you have entered any values for the Apple Team ID and Key ID fields?

**Comment by aakanshu** [comment]
Hi @poovamraj ,
I generated the client Id and other credentials and it worked for me. I guess some issue with dev credentials of Auth0. Thx for help
