### ISSUE TITLE
"Oops, something went wrong" screen

### ISSUE THREAD

**Issue by aksonov** [auth0-samples/auth0-react-native-sample#6]
I saw 'successful auth' and then redirected to that screen.
I've entered my tokens into auth0-credentilals.js and added 'allowed callback'. Is anything else I need to modify to run this demo successfully?

**Comment by cocojoe** [comment]
Please follow the QS and check the latest sample code https://auth0.com/docs/quickstart/native/react-native

Please reopen this issue if you run into any issues. Thx
