### ISSUE TITLE
Add a test for App.js

### ISSUE THREAD

**Issue by mraible** [auth0-samples/auth0-react-native-sample#78]
Is it possible to add a test for `App.js`? I already know Okta's React Native SDK and I'm trying to learn Auth0's. 

Okta has a sample with [a test for its `Auth` component](https://github.com/okta-samples/okta-react-native-sample/blob/main/tests/Auth-test.js). It would be useful if this example contained something similar.

**Comment by poovamraj** [comment]
Hi @mraible, we have plans to add integration test to our sample app similar to [auth0-flutter](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) sample app. We will note this to our back log as well. Thank you for your feedback

**Comment by poovamraj** [comment]
@mraible we have noted this in our backlog as SDK-3598. We are planning to address this in the next release. We will close this issue for now. Feel free to reopen it incase more information can be added.
