### ISSUE TITLE
App doesn't start on scanning qr code on IOS

### ISSUE THREAD

**Issue by khanzzirfan** [auth0-samples/auth0-react-native-sample#97]
App never works with IOS device.
start command is 
``` expo start --dev-client```

**Comment by khanzzirfan** [comment]
![image](https://user-images.githubusercontent.com/8625166/206894871-c46fd35f-a03c-4c1c-a996-99e4ea1d6750.png)

**Comment by poovamraj** [comment]
@khanzzirfan This sample works only with Expo Custom Dev Client or EAS build as we change the native code. 

You have to run your app on an emulator, simulator, or your own connected device.

To run the app on iOS run expo run:ios.
To run the app on Android run expo run:android.

We also have a PR to update the documentation to provide this info in the README file - https://github.com/auth0-samples/auth0-react-native-sample/pull/99.

We will close this for now but feel free to reopen it if you have more doubts
