### ISSUE TITLE
typescript

### ISSUE THREAD

**Issue by omniviewsports** [auth0-samples/auth0-react-native-sample#98]
When I attempt to follow the hooks sample using Typescript I keep getting an error saying that Auth0Provider cannot be used as a JSX element. Additionally, I get an error saying that auth) does not have an export, when I use "import { Auth0Provider } from 'react-native-auht0';

please advise.

**Comment by poovamraj** [comment]
Hi @omniviewsports I guess this is with respect to the type definitions not being updated in DefinitelyTyped. We have recently updated them here and this should be fixed now - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63584.

We will close this now. Please feel free to reopen it if you have doubts.
